incremental:
  init_cls: 10
  increment: 10

net:
  net_type: "SplitCosNet"
  backbone_type: "resnet18"

learner:
  learner_type: "APR"
  amp: False

loss:
  cls_lambda: 1.0
  kd_lambda: 10.0

init_optimizer:
  type: "sgd"
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  grad_accum: 1

incremental_optimizer:
  type: "sgd"
  lr: 0.01
  momentum: 0.9
  weight_decay: 2e-4
  grad_accum: 1

init_scheduler:
  type: "cos"
  total_epochs: 200

incremental_scheduler:
  type: "cos"
  total_epochs: 100

protos:
  normalize: True
  svd_k: Null
  gamma1_eval: 24

adc:
  do_adc: True
  adc_alpha: 25
  adc_sample_limit: 1000
  input_data_mode: "adcapr"
  attack: True
  batchsize: 64
  epochs: 9
  clamp_x: True
  trans_epochs: 64
  trans_lr: 1e-4
  colorjitter: False
  cifar10policy: False
  imagenetpolicy: False

apr:
  do_apr: True
  do_reproducible_trans: True
  perturb: True
  p_batchsize: 64
  perturb_alpha: 64
  loops: 4
  clamp_x: False
  apr_sample_limit: 200
  colorjitter: True
  cifar10policy: True
  imagenetpolicy: False
  proto_noise_mag: 1

data:
  cifar10policy: True
  cifar10colorjitter: True
  train:
    batch_size: 32
    init_batch_size: 64
    num_workers: 2
  test:
    init_batch_size: 128

log:
  interval: 20
  metrics: ["Linear", "Mahalanobis", "NCM"]
  use_tqdm: False
  ckpt_idx: []
  ckpt_tmpl: "apr_cifar100_task_{}.pth"
